- hosts: localhost
  tasks:
    - nomad:
        ID: "elasticsearch"
        Name: "elasticsearch"
        Datacenters:
          - "dev"
        Type: "service"
        TaskGroups:
          - Name: "elasticsearch"
            Tasks:
              - Name: "elasticsearch"
                Driver: "docker"
                Config:
                  image: "elasticsearch:7.3.1"
                  network_mode: "host"
                  dns_servers: ['localhost:8600']
                  volumes:
                    - "local:/usr/share/elasticsearch/data"
                    - "local/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
                Env:
                  discovery.type: single-node
                Resources:
                  CPU: 100
                  MemoryMB: 2048
                  Networks:
                    - MBits: 1
                      DynamicPorts:
                        - Label: "elasticsearch"
                          Value: 9200
                Templates:
                  - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/elasticsearch.yml.ctmpl') }}"
                    DestPath: "local/elasticsearch.yml"
                    ChangeMode: "signal"
                    ChangeSignal: "SIGHUP"
                Services:
                  - Name: "elasticsearch"
                    PortLabel: "elasticsearch"
                    Checks:
                      - Type: "http"
                        Path: "/_cluster/health"
                        Interval: 10_000_000_000
                        Timeout: 2_000_000_000
