- hosts: localhost
  tasks:
  - nomad_job:
      ID: "fluentbit"
      Name: "fluentbit"
      Datacenters:
        - "dev"
      Type: "system"
      TaskGroups:
      - Name: "fluentbit"
        Tasks:
          - Name: "fluentbit"
            Driver: "docker"
            Config:
              image: "{{fluentbit.image}}"
              network_mode: "host"
              dns_servers: ['localhost:{{consul.dns}}']
              volumes:
                - "local/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
                - "local:/fluent-bit/log"
                - "/var/log/syslog:/var/log/syslog.host:ro"
            Templates:
              - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/fluent-bit.conf.ctmpl') }}"
                DestPath: "local/fluent-bit.conf"
                ChangeMode: "signal"
                ChangeSignal: "SIGHUP"
            Resources:
              CPU: 200
              MemoryMB: 100
              Networks:
                - MBits: 1
                  ReservedPorts:
                    - Label: "forward"
                      Value: {{ fluentbit.port }}
            Services:
              - Name: "fluentbit"
                PortLabel: "forward"