- hosts: localhost
  tasks:
    - name: deploy job
      nomad_job:
        ID: "grafana"
        Name: "grafana"
        Datacenters:
         - "dev"
        Type: "service"
        TaskGroups:
          - Name: "grafana"
            Tasks:
            - Name: "grafana"
              Driver: "docker"
              Config:
                image: "{{grafana.image}}"
                network_mode: "host"
                dns_servers: ['localhost:{{consul.dns}}']
                volumes:
                  - "local:/var/lib/grafana"
              Resources:
                CPU: 100
                MemoryMB: 300
                Networks:
                - MBits: 1
                  ReservedPorts:
                  - Label: "http"
                    Value: {{ grafana.port }}
              Services:
              - Name: "grafana"
                PortLabel: "http"
                Checks:
                - Type: "http"
                  Path: "/api/health"
                  Interval: 10_000_000_000
                  Timeout: 2_000_000_000
