- hosts: localhost
  tasks:
    - name: build docker
      docker_image:
        build:
          path: /vagrant/docker/myapp
        name: "{{myapp.image}}"
        tag: "{{myapp.tag}}"
        push: yes
    - name: set vault policy for my app
      vault_policy:
        name: myapp
        capabilities:
          secret/myapp/*: ["create"]
    - name: init consul
      consul_kv_tree:
        path: openresty/endpoints/toto
        data:
          rules.json:
            - input:
                remote_addr: 0.0.0.0
              output:
                version: prod
                max_req: 100
                max_time: 60
            - output:
                version: dev
                max_req: 10
                max_time: 60
          type: uwsgi
          job.json:
            image: "{{myapp.image}}"
            disk: 300
            cpu: 300
            mbits: 1
            memory: 100
            policies: ["myapp"]
            uwsgi:
              threads: 2
              processes: 2
          restrictions.json:
            /app:
              - admin
          versions.json:
            prod: "{{myapp.tag}}"
            dev: "{{myapp.tag}}"
    - name: deploy job
      nomad_job:
        ID: celery_my_app
        Name: celery_my_app
        Datacenters: ["{{consul.datacenter}}"]
        Type: "service"
        TaskGroups:
        - Name: "celery"
          Tasks:
            - Name: "celery"
              Driver: "docker"
              Config:
                image: "{{myapp.image}}:{{myapp.tag}}"
                network_mode: "host"
                entrypoint: ["celery","-A","celery_app","worker"]
                volumes:
                  - "secrets/celery.json:/app/celery.json"
                logging:
                  type: "fluentd"
                  config:
                  - fluentd-address: "localhost:{{fluentbit.port}}"
                  - tag: "docker.myapp"
                  - fluentd-async-connect: "true"
              Env:
                CONSUL: ' {"host": "127.0.0.1", "port": {{consul.port}}, "timeout": 300}'
                FLUENTD: ' {"host": "127.0.0.1", "port": {{fluentbit.port}}, "timeout": 300}'
              Resources:
                CPU: 100
                MemoryMB: 100
              Templates:
                - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/celery.json.ctmpl') }}"
                  DestPath: "secrets/celery.json"
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
              Vault:
                  Policies: ["myapp"]
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
              Services:
              - Name: "toto"
                Tags: ["celery"]
                Checks:
                  - Type: "script"
                    Command: "celery"
                    Args: ["-A", "celery_app", "status"]
                    Interval: 10_000_000_000
                    Timeout: 2_000_000_000
      tags:
        - celery