- hosts: localhost
  tasks:
    - name: deploy job
      nomad_job:
        ID: "nexus"
        Name: "nexus"
        Datacenters:
          - "dev"
        Type: "service"
        TaskGroups:
          - Name: "nexus"
            Tasks:
              - Name: "nexus"
                Driver: "docker"
                Config:
                  image: "{{nexus.image}}"
                  network_mode: "host"
                  dns_servers: ['localhost:{{consul.dns}}']
                  volumes:
                    - "local:/nexus-data"
                  logging:
                    type: "fluentd"
                    config:
                    - fluentd-address: "localhost:{{fluentbit.port}}"
                    - fluentd-async-connect: "true"
                    - tag: "nexus"
                Env:
                  NEXUS_CONTEXT: "nexus"
                  INSTALL4J_ADD_VM_PARAMS: "-Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g  -Djava.util.prefs.userRoot=/root"
                Resources:
                  CPU: 100
                  MemoryMB: 1024
                  Networks:
                    - MBits: 1
                      ReservedPorts:
                        - Label: "http"
                          Value: 8081
                Services:
                  - Name: "nexus"
                    PortLabel: "http"
                    Checks:
                      - Type: "http"
                        Path: "/api/health"
                        Interval: 10_000_000_000
                        Timeout: 2_000_000_000
