- hosts: localhost
  tasks:
    - name: build docker
      docker_image:
        build:
          path: /vagrant/docker/openresty
        name: "{{openresty.image}}"
        tag: "{{openresty.tag}}"
        push: yes
        force_source: yes
        source: build
    - name: init consul
      consul_kv_tree:
        path: openresty
        data:
          endpoints:
          port: 80
          htpasswd:
    - name: deploy job
      nomad_job:
        ID: openresty
        Name: openresty
        Datacenters: ["{{consul.datacenter}}"]
        Type: "system"
        TaskGroups:
        - Name: "openresty"
          Tasks:
            - Name: "openresty"
              Driver: "docker"
              Config:
                image: "{{openresty.image}}:{{openresty.tag}}"
                network_mode: "host"
                volumes:
                  - "secrets/openresty.conf:/usr/local/openresty/nginx/conf/nginx.conf"
                  - "local/uwsgi_cache:/uwsgi_cache"
                  - "local/proxy_cache:/proxy_cache"
                logging:
                  type: "fluentd"
                  config:
                  - fluentd-address: "localhost:{{fluentbit.port}}"
                  - tag: "docker.openresty"
                  - fluentd-async-connect: "true"
              Env:
                OAUTH: ' {"client_id": "", "client_secret": "", "scope": "300", "response_type": "token", "signin_url": "", "details_url": ""}'
                REDIS: ' {"host": "127.0.0.1", "port": {{redis.port}}, "timeout": 300, "idle": 3600, "pool_size": 3}'
                RIAK: ' {"host": "127.0.0.1", "port": {{riak.port}}, "timeout": 300, "key": ""}'
                CONSUL: ' {"host": "127.0.0.1", "port": {{consul.port}}, "timeout": 300}'
                FLUENTD: ' {"host": "127.0.0.1", "port": {{fluentbit.port}}, "timeout": 300}'
                NOMAD: ' {"host": "127.0.0.1", "port": {{nomad.port}}, "timeout": 300}'
                NOMAD_TOKEN: '{{ loopup("env", "NOMAD_TOKEN") }}'
              Resources:
                CPU: 100
                MemoryMB: 100
                Networks:
                - MBits: 1
                  ReservedPorts:
                  - Label: "http"
                    Value: 80
              Templates:
                - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/openresty.conf.ctmpl') }}"
                  DestPath: "secrets/openresty.conf"
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
#                - EmbeddedTmpl: !unsafe '{{ keyOrDefault "openresty/htpasswd" "" }}'
#                  DestPath: "local/htpasswd"
#                  ChangeMode: "signal"
#                  ChangeSignal: "SIGHUP"
              Vault:
                  Policies: ["nomad-server"]
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
              Services:
              - Name: "openresty"
                PortLabel: "http"
                Tags: ["http"]
                Checks:
                  - Type: "http"
                    Path: "/status"
                    Interval: 10_000_000_000
                    Timeout: 2_000_000_000
#            - Name: "tcpdump"
#              Driver: "raw_exec"
#              Config:
#                command: "tcpdump"
#                args:
#                  - "-i"
#                  - "enp0s3:"
#                  - "port"
#                  - "80"
#                  - "and"
#                  - "'tcp[13]&4!=0'"
#                logging:
#                  type: "fluentd"
#                  config:
#                  - fluentd-address: "localhost:{{fluentbit.port}}"
#                  - tag: "tcpdump"
#                  - fluentd-async-connect: "true"
