- hosts: localhost
  tasks:
    - name: build docker
      docker_image:
        build:
          path: /vagrant/docker/openresty
        name: "{{openresty.image}}"
        tag: "{{openresty.tag}}"
        push: yes
    - name: init consul
      consul_kv_tree:
        path: openresty
        data:
          endpoints:
          port: 80
    - name: deploy job
      nomad_job:
        ID: openresty
        Name: openresty
        Datacenters: ["{{consul.datacenter}}"]
        Type: "system"
        TaskGroups:
          Name: "openresty"
          Tasks:
            - Name: "openresty"
              Driver: "docker"
              Config:
                image: "{{openresty.image}}:{{openresty.tag}}"
                network_mode: "host"
                volumes:
                  - "local/openresty.conf:/usr/local/openresty/nginx/conf/nginx.conf"
                  - "local/htpasswd:/etc/nginx/htpasswd"
                logging:
                  type: "fluentd"
                  config:
                  - fluentd-address: "localhost:{{fluentbit.port}}"
                  - tag: "openresty"
                  - fluentd-async-connect: "true"
              Env:
                OAUTH: "{'client_id': '', 'client_secret': '', 'scope': ''300'', 'response_type': 'token', 'signin_url': '', 'details_url': ''}"
                REDIS: "{'host': '127.0.0.1', 'port': {{redis.port}}, 'timeout': 300, 'idle': 3600, 'pool_size': 3}"
                RIAK: "{'host': '127.0.0.1', 'port': 8098, 'timeout': 300, 'key': ''}"
                CONSUL: "{''host': '127.0.0.1', 'port': {{consul.port}}, 'timeout': 300}"
                FLUENTD: "{'host': '127.0.0.1', 'port': {{fluentbit.port}}, 'timeout': 300}"
                NOMAD: "{'url':'http://127.0.0.1:{{nomad.port}}'}"
              Resources:
                CPU: 100
                MemoryMB: 500
                Networks:
                - MBits: 1
                  ReservedPorts:
                  - Label: "http"
                    Value: 80
              Templates:
                - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/openresty.conf.ctmpl') }}"
                  DestPath: "local/openresty.conf"
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
                - EmbeddedTmpl: !unsafe '{{ keyOrDefault "nginx/htpasswd" "" }}'
                  DestPath: "local/htpasswd"
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
              Services:
              - Name: "openresty"
                PortLabel: "http"
                Checks:
                  - Type: "http"
                    Path: "/status"
                    Interval: 10_000_000_000
                    Timeout: 2_000_000_000
            - ID: "tcpdump"
              Driver: "raw_exec"
              Config:
                command: "tcpdump"
                args:
                  - "-i"
                  - "enp0s3:"
                  - "port"
                  - "80"
                  - "and"
                  - "'tcp[13]&4!=0'"
                logging:
                  type: "fluentd"
                  config:
                  - fluentd-address: "localhost:{{fluentbit.port}}"
                  - tag: "tcpdump"
                  - fluentd-async-connect: "true"
