- hosts: localhost
  tasks:
    - name: install tcpdump
      apt: name=tcpdump

- hosts: localhost
  tasks:
    - name: build docker
      docker_image:
        build:
          path: .
        name: nexus.service.consul/paas/openresty
        tag: v1
        push: yes
    - name: init consul
      consul_kv_tree:
        path: openresty
        data:
          endpoints:
          port: 80
    - name: deploy job
      nomad:
        Name: openresty
        Datacenters: ["dev"]
        Type: "system"
        TaskGroups:
          Name: "openresty"
          Tasks:
            - Name: "openresty"
              Driver: "docker"
              Config:
                image: "nexus.service.consul/paas/openresty:v1"
                network_mode: "host"
                volumes:
                  - "local/openresty.conf:/usr/local/openresty/nginx/conf/nginx.conf"
                  - "local/htpasswd:/etc/nginx/htpasswd"
                logging:
                  type: "fluentd"
                  config:
                    fluentd-address: "localhost:24224"
                    tag: "openresty"
                    fluentd-async-connect: "true"
              Env:
                OAUTH: "{'client_id': '', 'client_secret': '', 'scope': ''300'', 'response_type': 'token', 'signin_url': '', 'details_url': ''}"
                REDIS: "{'host': '127.0.0.1', 'port': 6379, 'timeout': 300, 'idle': 3600, 'pool_size': 3}"
                RIAK: "{'host': '127.0.0.1', 'port': 8098, 'timeout': 300, 'key': ''}"
                CONSUL: "{''host': '127.0.0.1', 'port': 8500, 'timeout': 300}"
                FLUENTD: "{'host': '127.0.0.1', 'port': 24224, 'timeout': 300}"
                NOMAD: "{'url':'http://127.0.0.1:4646'}"
              Resources:
                CPU: 100
                MemoryMB: 100
                Networks:
                  MBits: 1
                  DynamicPorts:
                    Lavel: "http"
                    Value: 80
              Templates:
                - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/openresty.conf.ctmpl') }}"
                  destination: "local/openresty.conf"
                  change_mode: "signal"
                  change_signal: "SIGHUP"
                - EmbeddedTmpl: !unsafe '{{ keyOrDefault "nginx/htpasswd" "" }}'
                  destination: "local/htpasswd"
                  change_mode: "signal"
                  change_signal: "SIGHUP"
              Service:
                Name: "openresty"
                Port: "http"
                Checks:
                  - Type: "http"
                    Path: "/status"
                    Interval: "10s"
                    Timeout: "2s"
            - ID: "tcpdump"
              Driver: "raw_exec"
              Config:
                command: "tcpdump"
                args:
                  - "-i"
                  - "enp0s3:"
                  - "port"
                  - "80"
                  - "and"
                  - "'tcp[13]&4!=0'"
                logging:
                  type: "fluentd"
                  config:
                    fluentd_address: "localhost:24224"
                    tag: "tcpdump"
