- hosts: localhost
  tasks:
    - name: build docker
      docker_image:
        build:
          path: /vagrant/docker/postgres
        name: nexus.service.consul/paas/uwsgi
        tag: v1
        push: yes
    - name:
    - name: deploy job
      nomad:
        Name: pgbouncer
        Datacenters: ["dev"]
        Type: "service"
        TaskGroups:
        - Name: "pgbouncer"
          Tasks:
            - Name: "pgbouncer"
              Driver: "docker"
              Config:
                image: "pgbouncer"
                network_mode: "host"
                volumes:
                  - "local/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini"
                logging:
                  type: "fluentd"
                  config:
                    fluentd-address: "localhost:24224"
                    tag: "pgbouncer"
                    fluentd-async-connect: "true"
              Resources:
                CPU: 100
                MemoryMB: 100
                Networks:
                - MBits: 1
                  DynamicPorts:
                  - Label: "pgbouncer"
                    Value: 6543
              Templates:
                - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/pgbouncer.ini.ctmpl') }}"
                  DestPath: "local/pgbouncer.ini"
                  Change_mode: "signal"
                  Change_signal: "SIGHUP"
                - EmbeddedTmpl: ""
                  DestPath: "local/users.txt"
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
              Services:
                - Name: "pgbouncer"
                  PortLabel: "pgbouncer"
                  Checks:
                    - Type: "tcp"
                      Interval: 10_000_000_000
                      Timeout: 2_000_000_000