- hosts: localhost
  tasks:
    - name: build docker
      docker_image:
        build:
          path: /vagrant/docker/postgres
        name: "{{postgres.image}}"
        tag: "{{postgres.tag}}"
        push: yes
    - name: deploy job
      nomad_job:
        ID: postgres
        Name: postgres
        Datacenters: ["dev"]
        Type: "service"
        TaskGroups:
        - Name: "postgres"
          Tasks:
            - Name: "postgres"
              Driver: "docker"
              Config:
                image: "{{postgres.image}}:{{postgres.tag}}"
                network_mode: "host"
                volumes:
                  - "local:/var/lib/postgresql/data"
                logging:
                  type: "fluentd"
                  config:
                  - fluentd-address: "localhost:{{fluentbit.port}}"
                  - tag: "postgres"
                  - fluentd-async-connect: "true"
              Env:
                POSTGRES_USER: "postgres"
                POSTGRES_PASSWORD: "{{ postgres_password }}"
                POSTGRES_DB: "postgres"
              Resources:
                CPU: 100
                MemoryMB: 100
                Networks:
                - MBits: 1
                  ReservedPorts:
                  - Label: "postgres"
                    Value: "{{postgres.port}}"
              Templates:
                - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/postgres.conf.ctmpl') }}"
                  DestPath: "local/postgres.conf"
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
                - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/pg_hba.conf.ctmpl') }}"
                  DestPath: "local/pg_hba.conf"
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
              Services:
              - Name: "postgres"
                PortLabel: "postgres"
                Tags: ["postgres"]
                Checks:
                  - Type: "script"
                    Command: "/usr/bin/pg_isready"
                    Args: ["-h", "localhost", "-U", "postgres"]
                    Interval: 10_000_000_000
                    Timeout: 2_000_000_000
            - Name: "postgres_exporter"
              Driver: "exec"
              Config:
                command: "local/{{postgres_exporter.file}}"
              Artifacts:
                - Source: "{{postgres_exporter.url}}"
