- hosts: localhost
  tasks:
    - name: deploy job
      nomad_job:
        ID: "prometheus"
        Name: "prometheus"
        Datacenters:
         - "dev"
        Type: "service"
        TaskGroups:
          - Name: "prometheus"
            Tasks:
            - Name: "prometheus"
              Driver: "docker"
              Config:
                image: "{{prometheus.image}}"
                network_mode: "host"
                volumes:
                  - "local/prometheus.yml:/etc/prometheus/prometheus.yml"
              Templates:
                - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/prometheus.yml.ctmpl') }}"
                  DestPath: "local/prometheus.yml"
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
              Resources:
                CPU: 100
                MemoryMB: 100
                Networks:
                - MBits: 1
                  ReservedPorts:
                  - Label: "prometheus"
                    Value: "{{ prometheus.port }}"
              Services:
              - Name: "prometheus"
                PortLabel: "prometheus"
                Tags: ["urlprefix-/"]
                Checks:
                - Type: "http"
                  Path: "/-/healthy"
                  Interval: 10_000_000_000
                  Timeout: 2_000_000_000
