- hosts: localhost
  tasks:
    - name: set public settings
      consul_kv_tree:
        path: "redis"
        data:
          maxmemory: "{{redis.memory}}mb"
    - name: set private settings
      vault_secret:
        path: "redis"
        secret:
          password: 'totoleheros'
    - name: set vault policy for redis
      vault_policy:
        name: "redis-read"
        capabilities:
          secret/data/redis: ["read"]
    - name: deploy job
      nomad_job:
        ID: redis
        Name: redis
        Datacenters: ["{{consul.datacenter}}"]
        Type: "service"
        TaskGroups:
          - Name: "redis"
            Tasks:
              - Name: "redis"
                Driver: "docker"
                Config:
                  image: "{{redis.image}}"
                  network_mode: "host"
                  volumes:
                    - "secrets/redis.conf:/usr/local/etc/redis/redis.conf"
                  logging:
                    type: "fluentd"
                    config:
                      - fluentd-address: "localhost:{{fluentbit.port}}"
                      - tag: "docker.redis"
                      - fluentd-async-connect: "true"
                Resources:
                  CPU: 100
                  MemoryMB: "{{redis.memory}}"
                  Networks:
                    - MBits: 1
                      ReservedPorts:
                        - Label: "redis"
                          Value: "{{redis.port}}"
                Templates:
                  - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/redis.conf.ctmpl') }}"
                    DestPath: "secrets/redis.conf"
                    ChangeMode: "signal"
                    ChangeSignal: "SIGHUP"
                Vault:
                  Policies: ["redis-read"]
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
                Services:
                  - Name: "redis"
                    PortLabel: "redis"
                    Tags: ["redis"]
                    Checks:
                      - Type: "script"
                        Command: "redis-cli"
                        Args: ["ping"]
                        Interval: 10_000_000_000
                        Timeout: 2_000_000_000