- hosts: localhost
  tasks:
    - name: deploy job
      nomad:
        Name: redis
        Datacenters: ["dev"]
        Type: "service"
        TaskGroups:
        - Name: "redis"
          Tasks:
            - Name: "redis"
              Driver: "docker"
              Config:
                image: "redis"
                network_mode: "host"
                dns_servers: ['localhost:8600']
                volumes:
                  - "local/redis.conf:/usr/local/etc/redis/redis.conf"
                logging:
                  type: "fluentd"
                  config:
                    fluentd-address: "localhost:24224"
                    tag: "redis"
                    fluentd-async-connect: "true"
              Resources:
                CPU: 100
                MemoryMB: 100
                Networks:
                - MBits: 1
                  DynamicPorts:
                  - Label: "redis"
                    Value: 6543
              Templates:
                - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/redis.conf.ctmpl') }}"
                  DestPath: "local/redis.conf"
                  ChangeMode: "signal"
                  ChangeSignal: "SIGHUP"
              Services:
                - Name: "redis"
                  PortLabel: "redis"
                  Checks:
                    - Type: "script"
					  Command: "redis-cli"
					  Args: ["ping""]
                      Interval: 10_000_000_000
                      Timeout: 2_000_000_000