- hosts: localhost
  tasks:
    - name: build docker
      docker_image:
        build:
          path: /vagrant/docker/uwsgi
        name: "{{uwsgi.image}}"
        tag: "{{uwsgi.tag}}"
        push: yes
    - name: init consul
      consul_kv_tree:
        path: openresty
        data:
          endpoints:
            toto:
              rules.json:
                - input:
                    remote_addr: 0.0.0.0
                  output:
                    version: prod
                    max_req: 100
                    max_time: 60
                - output:
                    version: dev
                    max_req: 10
                    max_time: 60
              type: uwsgi
              job.json:
                image: "{{uwsgi.image}}"
                disk: 100
                cpu: 300
                mbits: 1
                memory: 300
                uwsgi:
                  threadss: 2
                  processes: 2
              restrictions.json:
                /app:
                  - admin
              versions.json:
                prod: v1
                dev: v1
          geo:
            zone:
              dev: default
              prod: 10.1.0.1,10.1.0.2
          port: 80
