---
# Consul is a service discovery
# https://www.consul.io/

- hosts: all
  become: True
  tasks:
    - name: Check that the consul.key exists
      stat: path=/etc/consul.key
      register: stat_result
    - block:
      - name: add user consul
        user: name=consul group=docker
      - name: create directories
        file: path=/usr/local/consul state=directory mode=0777 owner=consul group=docker
      - name: create directories
        file: path=/var/lib/consul state=directory mode=0777 owner=consul group=docker
      - name: download consul
        get_url: url="{{consul.url}}/{{consul.file}}" dest="/tmp/{{consul.file}}"
      - name: install zip
        apt: name=zip
      - name: unarchive consul
        unarchive: src="/tmp/{{consul.file}}" dest=/usr/local/bin/ mode=0755 copy=no
      - name: copy systemd unit
        template: src="../../resources/etc/systemd/system/consul.service" dest=/etc/systemd/system/  mode=0755 owner=consul group=docker
      - name: copy consul config
        template: src="../../templates/etc/consul.json" dest=/etc/consul.json  mode=0755 owner=consul group=docker
      - name: install psutil
        pip: name=psutil
      - name: install python consul
        pip: name=python-consul
      - name: install python hcl
        pip: name=pyhcl
      - name: copy script
        copy: src=../../resources/check_node.py dest=/usr/local/consul/check_node.py mode=0755
      - name: start consul
        systemd: name=consul state=started daemon_reload=yes enabled=yes
      - name: bootstrap acl
        uri: url="http://localhost:{{consul.port}}/v1/acl/bootstrap" method=PUT status=200 return_content=yes body_format=json
        register: _consul
        until: _consul.status == 200
        retries: 30
        delay: 5
      - name: save master key
        copy: content="{{_consul.json.SecretID}}" dest=/etc/consul.key mode=0640 group=docker
      - name: Set CONSUL_HTTP_TOKEN
        lineinfile:
          dest: /etc/environment
          state: present
          regexp: '^CONSUL_HTTP_TOKEN'
          line: 'CONSUL_HTTP_TOKEN={{_consul.json.SecretID}}'
      - name: Set CONSUL_HTTP_ADDR
        lineinfile:
          dest: /etc/environment
          state: present
          regexp: '^CONSUL_HTTP_ADDR'
          line: 'CONSUL_HTTP_ADDR=127.0.0.1:{{consul.port}}'
      - name: Set consul policies
        consul_acl:
          mgmt_token: "{{_consul.json.SecretID}}"
          rules:
            - key: ""
              policy: read
            - key: "vault"
              policy: deny
            - node: ""
              policy: read
            - service: ""
              policy: read
        register: _consul_anonymous
      - name: save consul anonymous token
        copy: content="{{_consul_anonymous.token}}" dest=/etc/consul_anonymous.key mode=0644 group=docker
      - name: set default token
        shell: "consul acl set-agent-token --token={{_consul.json.SecretID}} default {{_consul_anonymous.token}}"
      - name: copy resolved.conf
        copy: src=../../resources/etc/systemd/resolved.conf dest=/etc/systemd/resolved.conf mode=0644
      - name: restarting resolved
        service: name=system-resolved state=restarted daemon_reload=yes
      when: not stat_result.stat.exists
