---

- hosts: all
  become: True
  tasks:
    - name: add docker key
      apt_key: url="https://download.docker.com/linux/ubuntu/gpg"
    - name: add repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"
    - name: install docker
      apt: name=docker-ce update_cache=yes
    - name: Add the current user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: install pip
      apt: name=python3-pip
    - name: install ssl-match
      apt: name=python-backports.ssl-match-hostname
    - name: install py-docker
      pip: name=docker
    - name: reset connection to allow user changes to affect 'current login user'
      meta: reset_connection
    - name: copy docker conf
      template: src=../../resources/etc/docker/daemon.json dest=/etc/docker/ owner="{{ ansible_user }}" group=docker mode=0640
    - name: create /etc/systemd/system/docker.service.d
      file: path=/etc/systemd/system/docker.service.d state=directory group=docker mode=0750
#    - name: copy docker override
#      template: src=../../resources/etc/systemd/system/docker.service.d/override.conf dest=/etc/systemd/system/docker.service.d/ owner="{{ ansible_user }}" group=docker mode=0640
    - name: restart docker
      service: name=docker state=restarted
    - name: copy docker profile
      copy: src=../../resources/etc/profile.d/docker.sh dest=/etc/profile.d group=docker mode=0644
    - name: create /etc/environment.d
      file: path=/etc/environment.d state=directory mode=0755
    - name: copy docker profile
      copy: content="" dest=/etc/environment.d/docker group=docker mode=0660
