---

- hosts: all
  become: True
  tasks:
    - name: install docker
      apt: name=docker.io
    - name: Add the current user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: install pip
      apt: name=python-pip
    - name: install ssl-match
      apt: name=python-backports.ssl-match-hostname
    - name: install docker
      pip: name=docker
    - name: reset connection to allow user changes to affect 'current login user'
      meta: reset_connection
    - name: copy docker conf
      copy: src=../../resources/etc/docker/daemon.json dest=/etc/docker/ owner=docker group=docker mode=0660
    - name: restart docker
      service: name=docker state=restarted

