---
# Fluentbit is a log forwarder (to elastic search, sentry or other db)
# https://www.fluentbit.io/

- hosts: all
  become: True
  tasks:
    - name: add user fluentbit
      user: name=fluentbit group=docker
    - name: add fluentbit key
      apt_key: url=http://packages.fluentbit.io/fluentbit.key
    - name: copy conf systemd
      copy: content="deb http://packages.fluentbit.io/ubuntu/bionic bionic main" dest=/etc/apt/sources.list.d/fluentbit.list
    - name: install td-agent-bit
      apt: name=td-agent-bit update_cache=yes
    - name: make dir
      file: path=/var/log/td-agent-bit state=directory mode=0777 owner=fluentbit group=docker
    - name: copy conf fluentbit
      copy: src="../../resources/etc/td-agent-bit/td-agent-bit.conf" dest=/etc/td-agent-bit/td-agent-bit.conf owner=fluentbit
    - name: copy conf parsers
      copy: src="../../resources/etc/td-agent-bit/my_parsers.conf" dest=/etc/td-agent-bit/my_parsers.conf owner=fluentbit
    - name: start td-agent-bit
      systemd: name=td-agent-bit state=started daemon_reload=yes enabled=yes
