- hosts: localhost
  tasks:
  - nomad_job:
      ID: "fluentbit"
      Name: "fluentbit"
      Datacenters:
        - "{{consul.datacenter}}"
      Type: "system"
      TaskGroups:
      - Name: "fluentbit"
        Tasks:
          - Name: "fluentbit"
            Driver: "docker"
            Config:
              image: "{{fluentbit.image}}"
              network_mode: "host"
              volumes:
                - "secrets/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
                - "secrets/parsers.conf:/fluent-bit/etc/parsers.conf"
                - "/var/log/fluentbit:/log/"
                - "/var/log/syslog:/var/log/syslog.host:ro"
            Templates:
              - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/fluent-bit.conf.ctmpl') }}"
                DestPath: "secrets/fluent-bit.conf"
                ChangeMode: "restart"
              - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/parsers.conf.ctmpl') }}"
                DestPath: "secrets/parsers.conf"
                ChangeMode: "restart"
            Resources:
              CPU: 200
              MemoryMB: 100
              Networks:
                - MBits: 1
                  ReservedPorts:
                    - Label: "forward"
                      Value: "{{ fluentbit.port }}"
            Services:
              - Name: "fluentbit"
                Tags: ["fluentd"]
                PortLabel: "forward"