- hosts: localhost
  tasks:
    - name: deploy job
      nomad_job:
        ID: "confluence"
        Name: "confluence"
        Datacenters:
         - "{{consul.datacenter}}"
        Type: "service"
        TaskGroups:
          - Name: "confluence"
            Tasks:
            - Name: "confluence"
              Driver: "docker"
              Config:
                image: "{{confluence.image}}"
                network_mode: "host"
                volumes:
                  - "local:/var/atlassian/application-data/confluence"
              Env:
                CATALINA_CONTEXT_PATH: confluence
              Resources:
                CPU: 100
                MemoryMB: 1024
                Networks:
                - MBits: 1
                  ReservedPorts:
                  - Label: "http"
                    Value: "{{ confluence.port }}"
              Services:
              - Name: "confluence"
                PortLabel: "http"
                Tags: ["http"]
                Checks:
                - Type: "http"
                  Path: "/confluence/status"
                  Interval: 10_000_000_000
                  Timeout: 2_000_000_000
