- hosts: localhost
  tasks:
    - nomad_job:
        ID: "elasticsearch"
        Name: "elasticsearch"
        Datacenters:
          - "{{consul.datacenter}}"
        Type: "service"
        TaskGroups:
          - Name: "elasticsearch"
            Tasks:
              - Name: "elasticsearch"
                Driver: "docker"
                Config:
                  image: "{{elasticsearch.image}}"
                  network_mode: "host"
                  volumes:
                    - "local:/usr/share/elasticsearch/data"
                    - "secrets/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
                Env:
                  discovery.type: single-node
                Resources:
                  CPU: 100
                  MemoryMB: 2048
                  Networks:
                    - MBits: 1
                      ReservedPorts:
                        - Label: "http"
                          Value: "{{ elasticsearch.http_port }}"
                        - Label: "transport"
                          Value: "{{ elasticsearch.transport_port }}"
                Templates:
                  - EmbeddedTmpl: "{{ lookup('file','../../resources/go-templates/elasticsearch.yml.ctmpl') }}"
                    DestPath: "secrets/elasticsearch.yml"
                    ChangeMode: "signal"
                    ChangeSignal: "SIGHUP"
                Services:
                  - Name: "elasticsearch"
                    PortLabel: "http"
                    Tags: ["http"]
                    Checks:
                      - Type: "http"
                        Path: "/_cluster/health"
                        Interval: 10_000_000_000
                        Timeout: 2_000_000_000
