- hosts: localhost
  tasks:
    - name: deploy job
      nomad_job:
        ID: "jira"
        Name: "jira"
        Datacenters:
         - "{{consul.datacenter}}"
        Type: "service"
        TaskGroups:
          - Name: "jira"
            Tasks:
            - Name: "jira"
              Driver: "docker"
              Config:
                image: "{{jira.image}}"
                network_mode: "host"
                volumes:
                  - "local:/var/atlassian/application-data/jira"
              Env:
                JVM_MINIMUM_MEMORY: 1024m
                JVM_MAXIMUM_MEMORY: 1024m
                ATL_TOMCAT_PORT: "{{ jira.port }}"
                CATALINA_CONTEXT_PATH: jira
              Resources:
                CPU: 100
                MemoryMB: 1024
                Networks:
                - MBits: 1
                  ReservedPorts:
                  - Label: "http"
                    Value: "{{ jira.port }}"
              Services:
              - Name: "jira"
                PortLabel: "http"
                Tags: ["http"]
                Checks:
                - Type: "http"
                  Path: "/jira/status"
                  Interval: 10_000_000_000
                  Timeout: 2_000_000_000
