- hosts: localhost
  tasks:
    - name: create docker-volume
      docker_volume: name=nexus-data
    - name: deploy job
      nomad_job:
        ID: "nexus"
        Name: "nexus"
        Datacenters:
          - "{{consul.datacenter}}"
        Type: "service"
        TaskGroups:
          - Name: "nexus"
            Tasks:
              - Name: "nexus"
                Driver: "docker"
                Config:
                  image: "{{nexus.image}}"
                  network_mode: "host"
                  volume_driver: 'local'
                  volumes:
                    - "nexus-data:/nexus-data"
                  logging:
                    type: "fluentd"
                    config:
                    - fluentd-address: "localhost:{{fluentbit.port}}"
                    - fluentd-async-connect: "true"
                    - tag: "docker.nexus"
                Env:
                  NEXUS_CONTEXT: "nexus"
                  INSTALL4J_ADD_VM_PARAMS: "-Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g  -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
                Resources:
                  CPU: 1000
                  MemoryMB: 2048
                  Networks:
                    - MBits: 1
                      ReservedPorts:
                        - Label: "http"
                          Value: "{{nexus.port}}"
                Services:
                  - Name: "nexus"
                    PortLabel: "http"
                    Checks:
                      - Type: "http"
                        Path: "/nexus/service/rest/v1/status"
                        Interval: 10_000_000_000
                        Timeout: 2_000_000_000
