- hosts: localhost
  tasks:
    - name: deploy job
      nomad_job:
        ID: "rundeck"
        Name: "rundeck"
        Datacenters:
         - "{{consul.datacenter}}"
        Type: "service"
        TaskGroups:
          - Name: "rundeck"
            Tasks:
            - Name: "rundeck"
              Driver: "docker"
              Config:
                image: "{{rundeck.image}}"
                network_mode: "host"
                volumes:
                  - "local:/home/rundeck/server/data"
                  - "/home/{{ ansible_user }}/.ssh://home/rundeck/.ssh"
              Resources:
                CPU: 100
                MemoryMB: 800
                Networks:
                - MBits: 1
                  ReservedPorts:
                  - Label: "http"
                    Value: "{{ rundeck.port }}"
              Services:
              - Name: "rundeck"
                PortLabel: "http"
                Tags: ["http"]
                Checks:
                - Type: "http"
                  Path: "/api/2/system/info"
                  Interval: 10_000_000_000
                  Timeout: 2_000_000_000
