FROM rundeck/rundeck:3.1.0

RUN cd /home/rundeck/libext && \
    wget https://github.com/ValFadeev/rundeck-nomad-plugin/releases/download/v0.1.0/rundeck-nomad-plugin-0.1.0.jar \
    wget https://github.com/rundeck-plugins/docker/releases/download/1.4.1/docker-container-1.4.1.zip \
